/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT flexivision.cdb */

/*  Include Header File  */
#include "flexivisioncfg.h"


#ifdef __cplusplus
#pragma CODE_SECTION(".text:CSL_cfgInit")
#else
#pragma CODE_SECTION(CSL_cfgInit,".text:CSL_cfgInit")
#endif


#ifdef __cplusplus
#pragma FUNC_EXT_CALLED()
#else
#pragma FUNC_EXT_CALLED(CSL_cfgInit)
#endif

/*  Config Structures */
EDMA_Config edmaCfg0 = {
    0x21300000,        /*  Option  */
    0x000AAAAA,        /*  Source Address - Numeric   */
    0x00000100,        /*  Transfer Counter - Numeric  */
    0xBBBBBBBB,        /*  Destination Address - Numeric   */
    0x00000004,        /*  Index register - Numeric  */
    0x00000000         /*  Element Count Reload and Link Address  */
};

EMIFA_Config emifaCfgSDRAM = {
    0x000220E4,        /*  Global Control Reg. (GBLCTL)   */
    0xFFFFFFD3,        /*  CE0 Space Control Reg. (CECTL0)   */
    0xFFFFFF23,        /*  CE1 Space Control Reg. (CECTL1)   */
    0xFFFFFF23,        /*  CE2 Space Control Reg. (CECTL2)   */
    0xFFFFFF23,        /*  CE3 Space Control Reg. (CECTL3)   */
    0x6348F000,        /*  SDRAM Control Reg.(SDCTL)   */
    0x005DC5DC,        /*  SDRAM Timing Reg.(SDTIM)   */
    0x00175F3F,        /*  SDRAM Extended Reg.(SDEXT)   */
    0x00000002,        /*  CE0 Space Secondary Control Reg. (CESEC0)  */
    0x00000002,        /*  CE1 Space Secondary Control Reg. (CESEC1)  */
    0x00000002,        /*  CE2 Space Secondary Control Reg. (CESEC2)  */
    0x00000002         /*  CE3 Space Secondary Control Reg. (CESEC3)  */
};

EMIFB_Config emifbCfg0 = {
    0x000120C4,        /*  Global Control Reg. (GBLCTL)   */
    0xFFFFFFB3,        /*  CE0 Space Control Reg. (CECTL0)   */
    0xFFFFFF03,        /*  CE1 Space Control Reg. (CECTL1)   */
    0xFFFFFF03,        /*  CE2 Space Control Reg. (CECTL2)   */
    0xFFFFFF03,        /*  CE3 Space Control Reg. (CECTL3)   */
    0x0348F000,        /*  SDRAM Control Reg.(SDCTL)   */
    0x005DC5DC,        /*  SDRAM Timing Reg.(SDTIM)   */
    0x00175F3F,        /*  SDRAM Extended Reg.(SDEXT)   */
    0x00000043,        /*  CE0 Space Secondary Control Reg. (CESEC0)  */
    0x00000002,        /*  CE1 Space Secondary Control Reg. (CESEC1)  */
    0x00000002,        /*  CE2 Space Secondary Control Reg. (CESEC2)  */
    0x00000002         /*  CE3 Space Secondary Control Reg. (CESEC3)  */
};

/*  Handles  */

/*
 *  ======== CSL_cfgInit() ========  
 */
void CSL_cfgInit()
{
    EMIFA_config(&emifaCfgSDRAM);
    EMIFB_config(&emifbCfg0);
}
